# This is workflow runs on push
#
name: Release

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  push:
    branches: [main, next, beta, alpha]

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  npm-lint:
    name: '▶️ actions'
    uses: ./.github/workflows/npm-lint.yml

  codeql:
    name: '▶️ actions'
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  release:
    name: '▶️ actions'
    needs: [npm-lint, codeql]
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
