# This is workflow runs on push
#
name: Pull Request Check

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: PR_${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: '▶️ actions'
    uses: ./.github/workflows/lint-pr.yml

  npm-lint:
    name: '▶️ actions'
    needs: [lint-pr]
    uses: ./.github/workflows/npm-lint.yml

  docker:
    name: '▶️ actions'
    needs: [npm-lint]
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write

  codeql:
    name: '▶️ actions'
    needs: [lint-pr]
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  dependencies:
    name: '▶️ actions'
    uses: ./.github/workflows/dependencies.yml
    permissions:
      pull-requests: write
      contents: write
